### ISSUE TITLE
Relational tables don't seem to work anymore - rewrite!

### ISSUE THREAD

**Issue by blekerfeld** [blekerfeld/donut#12]

**Comment by blekerfeld** [comment]
Relational tables are a bit strange anyway, maybe find something else altogether

**Comment by blekerfeld** [comment]
But if someone wants to take a look as to the bug in the relational tables, be my guest.

**Comment by nedroden** [comment]
What bug are we talking about here?

**Comment by blekerfeld** [comment]
Try add links between entries in the manegemant panel and you will see, I am not sure what it is exactly. The wrong data is being loaded or something... it is part of the first OOP code I wrote for donut, so it might not be that smooth compared to the rest.

**Comment by nedroden** [comment]
Links between words and translations seems to work fine for me. How is the wrong data being loaded? A wrong row?

**Comment by blekerfeld** [comment]
Relational tables are obeslete in Donut, code rests will be removed shortly...
