### ISSUE TITLE
No such file or directory - Dispatch.php

### ISSUE THREAD

**Issue by nedroden** [blekerfeld/donut#22]
Hello,

code/classes/dispatcher.cset.php contains a line that calls for a file named "code/Dispatch.php", but on case-sensitive server configurations that would throw an error.

In code/classes/dispatch.cset.php, replacing
```
$this->_dispatchData = require_once p::FromRoot("code/Dispatch.php");
```
with
```
$this->_dispatchData = require_once p::FromRoot("code/dispatch.php");
```
solves the problem.

**Comment by blekerfeld** [comment]
Thanks for noticing, it will be fixed! :)
