### ISSUE TITLE
Several syntax errors

### ISSUE THREAD

**Issue by nedroden** [blekerfeld/donut#28]
This line in /code/classes/DataModel.cset.php (line 200) gives a syntax error:
```$count = (p::$db->cacheQuery("SELECT count(id) AS total FROM ".$this->_table." ".$this->_condition.";"))->fetchObject();```

Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in {...}/code/classes/DataModel.cset.php on line 200

The same error occurs in InflectionTable.cset.php on line 36 and IrregularTable.cset.php on lines 37, 39 and 42. It's possible you can instantiate a class and invoke a method on it in one line, but can't invoke a method on the result of a method if you but parentheses around them (which is weird, since it's basically the same thing). Anyway, removing the parentheses like this fixes the issue:
```$count = p::$db->cacheQuery("SELECT count(id) AS total FROM ".$this->_table." ".$this->_condition.";")->fetchObject();```

Form.cset.php gives an 'Unexpected character '[' error on lines 194 and 195, but this can be solved by replacing
```				pDataField::addToStack($key, ($this->dataModel->data()->fetchAll()[0])[$this->_showField]);
				$output .= ($this->dataModel->data()->fetchAll()[0])[$this->_showField];
```
with
```								pDataField::addToStack($key, $this->dataModel->data()->fetchAll()[0][$this->_showField]);
				$output .= $this->dataModel->data()->fetchAll()[0][$this->_showField];
```

Line 220 in LemmaSheetDataModel.cset.php, an 'uxpected new' error occurs. 'new' is a resolved keyword, renaming it should fix the issue. In the same file, on line 297, the following line causes a 'Fatal error: Cannot use isset() on the result of a function call (you can use "null !== func()" instead)'
```if(isset($dM->data()->fetchAll()[0]))```
Replacing it with something like this fixes the issue:
```if(array_key_exists(0, $dM->data()->fetchAll()))```

The same error occurs in SetHandler.cset.php on lines 65 and 76. Changing that line to the line above (but replacing data() with getObjects() fixes the issue. In User.cset.php, the issue also occurs but can be solved using the same line as in LemmaSheetDataModel.cset.php.

In User.cset.php the following line gives an error (Strict Standards: Non-static method pUser::load() should not be called statically):
```return self::load(self::$dataModel->data()->fetchAll()[0]);```

Since you don't have an object (non-static methods can use static methods, but static methods cannot use non-static methods (since static methods are not part of any particular object)). I haven't looked at how to fix this one, but I'll let you know.

Dispatcher.cset.php calls to ```code/Dispatch.php```, but since that file doesn't exist, it fails. It can be fixed by replacing the following line:
```$this->_dispatchData = require_once p::FromRoot("code/Dispatch.php");```
to
```$this->_dispatchData = require_once p::FromRoot("code/dispatch.php");```

Since I have already applied the changes (apart from the user loading issue) myself, I'll submit a pull request within the next 15 minutes.

Build: 93b0877
PHP version: 5.6.31

**Comment by nedroden** [comment]
Okay, so apparently there is something wrong with my hosting as, apparently, PHP7.1.7 is the same as PHP 5.6.31.

Anyway, some of these issues do not occur on my localhost (I'll have to check for the syntax errors), but you just cannot call a non-static method statically.

**Comment by nedroden** [comment]
Regarding the user loading issue, making the load method static seems to work.

**Comment by blekerfeld** [comment]
Thanks for taking the time to report this and even for fixing where it goes wrong, I'll be awaiting your pull request! :)

**Comment by nedroden** [comment]
No problem, glad to help!
