### ISSUE TITLE
Database structure - check everything

### ISSUE THREAD

**Issue by blekerfeld** [blekerfeld/donut#30]
Check all foreign keys, to solve #27

**Comment by nedroden** [comment]
Deleting languages that don't have any foreign keys referencing them works fine. You could have a warning message display if there are any words, translations, etc for that language. The user would then have the option to either abort or delete everything associated with the language.

**Comment by blekerfeld** [comment]
The problem we had with some languages was also because one out of use foreign key field that restricted deleting, from the old donut when there still was one editor language per user. 

Anyway, the latest commit has a cleaned up database! :)
