### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by nedroden** [blekerfeld/donut#49]
Have you considered using namespaces? Basically, what you'd be able to do is have multiple classes with the same name. You're currently prefixing all classes with 'p' to avoid class collision, right? Well, if you're using namespaces, you wouldn't have to worry about that.

Again it's just a suggestion, but you might find namespaces to be very convenient.

**Comment by blekerfeld** [comment]
Could you give some examples of how you're using namespaces in Draiwiki, for example?

**Comment by blekerfeld** [comment]
I mean, how does it work with "use"? Is the file in some mystical way only loaded if some other file requires a class in it via use?

**Comment by nedroden** [comment]
Well, since DraiWiki makes use of the MVC model and its classes are divided into 'packages', this is how they are used there:

DraiWiki\src\main\controllers - For controllers belonging to the 'main package'. The DraiWiki part, obviously, refers to the entire project (you should definitely include the project name), while the src part refers to code outside the public directory (which basically means everything apart from routing, templates and a few other files).
DraiWiki\src\main\models - Same as above, but this namespace only contains models.

For example:
```<?php
namespace DraiWiki\src\main\models;

class Article {

}
```
You could, for example, do something like this:
```
<?php
namespace DraiWiki\src\main\controllers;

use DraiWiki\src\main\models\Article as Model;

class Article {
    private $_model;

    public function __construct() {
        $this->_model = new Model(); // Refers to the Article class in the model namespace
    }

    .... code ....
}
```

Dividing your classes like this is actually really helpful because it separates parts of your code in a way that makes it easier to understand (since you can see what's part of what).

**Comment by blekerfeld** [comment]
Postponed to final stage
