### ISSUE TITLE
Email activation

### ISSUE THREAD

**Issue by nedroden** [blekerfeld/donut#54]
To prevent spam, it would help if users needed to enter an activation code (sent to their email) before getting access to areas only available to members.

You might find the following library helpful: https://github.com/eoghanobrien/php-simple-mail (released under the MIT license)

**Comment by blekerfeld** [comment]
Thanks for the request. I would definitly like a way to prevent spam account, but I would also want to not make it too difficult to use Donut. Having e-mail activation would be very nice, but it would add a mail server as a requirement... so I looked at the new reCHAPTCHA (the one with [ ] I am not a robot), which requires an API key for the domain it is being used on... not sure which one would be better. 

This is also why I still not made a registration page...

**Comment by nedroden** [comment]
You _could_ implement both by making both optional, because indeed, e-mail activation would require an e-mail server. That way it could still be used on localhost (since setting up an SMTP server seems to be a PITA to set up) and people who prefer direct registration would be satisfied as well. Just a suggestion, of course.

reCAPTACHA would definitely be an effective anti-spam measure, so it would be good to add that either way.

**Comment by blekerfeld** [comment]
E-mail activation: done
