### ISSUE TITLE
Help sections for terminal commands

### ISSUE THREAD

**Issue by nedroden** [blekerfeld/donut#65]
It would be cool if adding a command after 'help' would display a help page containing information about the command. For example, if one were to run ``help shell``, information would be given about that command:

> shell - Usage: shell [argument 1] {optional argument}

**Comment by blekerfeld** [comment]
Thanks for the request! (wow, took me so long to answer :O).

I will not do this untill the very final stage, and only if the terminal is there to keep, I build it as a tool to test the twolc rules easily, it might get replaced by multiple gui implantations of the terminal commands.
