### ISSUE TITLE
Any toughts on the tablesheet-layout?

### ISSUE THREAD

**Issue by blekerfeld** [blekerfeld/donut#67]
The tablesheet-structure will be used for creating new inflection categories (nouns etc.) and managing their inflection tables. Is this lay-out straight-forward enough?

![knipsel](https://user-images.githubusercontent.com/13293128/29878420-c670afd2-8da2-11e7-88ea-404eed2ccfa1.PNG)

**Comment by nedroden** [comment]
It looks really cool; the table preview especially should be really helpful. Columns would be used for things like multiple tenses, correct?

One small thing, though: could you make the input box font a little bigger?
